server:
  port: 8087

spring:
  application:
    name: order-service
  #  profiles: local
  zipkin:
    sender:
      type: kafka
  sleuth:

#    trace-id128: true
    sampler:
      probability: 1.0



  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  kafka:
    bootstrap-servers:
    - localhost:9092
    template:
      default-topic: test-order

    producer:
      properties:
        value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test
      properties:
        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "eu.senla.event.model"
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    eu.senla: DEBUG
    org.springframework.web : debug
#  pattern:
#    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"