server:
  port: 8089

spring:
  application:
    name: kitchen-service

  zipkin:
    sender:
      type: kafka
  sleuth:
#    trace-id128: true
    sampler:
      probability: 1.0

  kafka:
    bootstrap-servers:
      - localhost:9092
    template:
      default-topic: test-order
    producer:
      properties:
        value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: test
      properties:
        value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "eu.senla.event.model"

logging:
  level:
    eu.senla: DEBUG
    org.springframework.web : debug

#  pattern:
#    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"